export default {
  LOGIN: 'LOGIN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  APP_DATA: 'APP_DATA',
  NO_INTERNET: "NO_INTERNET",
  UPDATE_LOC:'UPDATE_LOC',
  ADD:'ADD',
  ADD_To_CART:'ADD_To_CART',
  ADD:'ADD',
  DELETE:'DELETE',
  TOTAL:'TOTAL',
  EDIT:'EDIT',
  INCREASE:'INCREASE',
  DECREASE:'DECREASE'
};
